# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: itinerary.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fitinerary.proto\x12\titinerary\"+\n\x13GetItineraryRequest\x12\x14\n\x0citinerary_id\x18\x01 \x01(\t\"!\n\x11GetItineraryReply\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t2Y\n\tItinerary\x12L\n\x0cGetItinerary\x12\x1e.itinerary.GetItineraryRequest\x1a\x1c.itinerary.GetItineraryReplyB\x16\xaa\x02\x13\x63ontracts.itineraryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'itinerary_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\023contracts.itinerary'
  _globals['_GETITINERARYREQUEST']._serialized_start=30
  _globals['_GETITINERARYREQUEST']._serialized_end=73
  _globals['_GETITINERARYREPLY']._serialized_start=75
  _globals['_GETITINERARYREPLY']._serialized_end=108
  _globals['_ITINERARY']._serialized_start=110
  _globals['_ITINERARY']._serialized_end=199
# @@protoc_insertion_point(module_scope)
